web:
  - name: gearup-api
    runtime: node@22
    build_command: npm install --include=dev && npm run prisma:generate && npm run build
    start_command: npm run prisma:migrate:deploy && npm start
    health_check:
      path: /api/auth/me
      interval: 30
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: APP_URL
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
      - key: BCRYPT_SALT_ROUNDS
        value: "12"
        scope: RUN_AND_BUILD_TIME
      - key: JWT_ACCESS_SECRET
        scope: RUN_AND_BUILD_TIME
      - key: JWT_REFRESH_SECRET
        scope: RUN_AND_BUILD_TIME
      - key: JWT_ACCESS_EXPIRES_IN
        value: "1d"
        scope: RUN_AND_BUILD_TIME
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
        scope: RUN_AND_BUILD_TIME
      - key: STRIPE_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_AND_BUILD_TIME
      - key: STRIPE_PRODUCT_PRICE_ID
        scope: RUN_AND_BUILD_TIME
